export const LOAD_POLLS_SUCCESS = 'LOAD_POLLS_SUCCESS';
export const VOTE_SUCCESS = 'VOTE_SUCCESS';
export const CREATE_POLL_SUCCESS = 'CREATE_POLL_SUCCESS';
export const DELETE_POLL_SUCCESS = 'DELETE_POLL_SUCCESS';

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const AUTH_USER = 'AUTH_USER';
export const UNAUTH_USER = 'UNAUTH_USER';
export const AUTH_ERROR = 'AUTH_ERROR';